package reconciliation

import (
	"crypto/ed25519"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"
)

const (
	FixtureOnlyScope = "fixture-only"

	ImportStatusApplied    = "applied"
	ImportStatusPaused     = "paused"
	ImportStatusCompleted  = "completed"
	ImportStatusIdempotent = "idempotent"
	ImportStatusRolledBack = "rolled_back"

	checkpointNew        = "new"
	checkpointRunning    = "running"
	checkpointPaused     = "paused"
	checkpointCompleted  = "completed"
	checkpointRolledBack = "rolled_back"
)

var (
	ErrManifestBlocked          = errors.New("manifest contains blocked or unresolved proposals")
	ErrManifestApprovalRequired = errors.New("explicit fixture approval is required")
	ErrManifestSignature        = errors.New("manifest signature is invalid")
	ErrManifestIntegrity        = errors.New("manifest identity is invalid")
	ErrCheckpointIntegrity      = errors.New("fixture checkpoint integrity is invalid")
	ErrCheckpointManifest       = errors.New("fixture checkpoint belongs to another manifest")
	ErrInvalidCheckpointKey     = errors.New("fixture checkpoint key must be at least 32 bytes")
	ErrInvalidExecutionTime     = errors.New("execution time is required")
	ErrImportAlreadyReversed    = errors.New("fixture manifest has already been rolled back")
)

// ManifestApproval is explicit operator evidence. It is not generated by the
// importer and is included in the signed manifest.
type ManifestApproval struct {
	OperatorID string `json:"operator_id"`
	ApprovedAt string `json:"approved_at"`
	Reason     string `json:"reason"`
	Scope      string `json:"scope"`
}

// ManifestRecord is the minimum import-shaped fact needed by the fixture
// rehearsal. Raw canonical keys and personal data are never copied.
type ManifestRecord struct {
	Entity         EntityKind  `json:"entity"`
	PlatformID     string      `json:"platform_id"`
	MatchKeySHA256 string      `json:"match_key_sha256"`
	SourceRefs     []SourceRef `json:"source_refs"`
}

// Manifest is a signed, fixture-only import plan. It does not authorize a
// Platform database write or a CTRL/IMS cutover.
type Manifest struct {
	SchemaVersion int               `json:"schema_version"`
	ManifestID    string            `json:"manifest_id"`
	ReportSHA256  string            `json:"report_sha256"`
	Scope         string            `json:"scope"`
	Records       []ManifestRecord  `json:"records"`
	Approval      *ManifestApproval `json:"approval,omitempty"`
}

// SignedManifest is the operator-approved manifest envelope.
type SignedManifest struct {
	Manifest  Manifest `json:"manifest"`
	Algorithm string   `json:"algorithm"`
	Signature string   `json:"signature"`
}

// BuildManifest converts an entirely proposed report into an ordered,
// reviewable fixture manifest. Any blocked, ambiguous or colliding proposal
// fails closed and cannot be partially imported.
func BuildManifest(report Report) (Manifest, error) {
	if report.SchemaVersion != SchemaVersion || report.ReportType != "platform.reconciliation.inventory.v1" {
		return Manifest{}, ErrManifestIntegrity
	}
	if len(report.Proposals) == 0 {
		return Manifest{}, ErrManifestBlocked
	}
	records := make([]ManifestRecord, 0, len(report.Proposals))
	seenPlatformIDs := make(map[string]struct{}, len(report.Proposals))
	for _, proposal := range report.Proposals {
		if proposal.Status != StatusProposed || !proposal.ReviewRequired || proposal.PlatformID == "" || proposal.MatchKeySHA256 == "" || len(proposal.SourceRefs) == 0 {
			return Manifest{}, ErrManifestBlocked
		}
		if _, exists := seenPlatformIDs[proposal.PlatformID]; exists {
			return Manifest{}, ErrManifestIntegrity
		}
		seenPlatformIDs[proposal.PlatformID] = struct{}{}
		records = append(records, ManifestRecord{
			Entity:         proposal.Entity,
			PlatformID:     proposal.PlatformID,
			MatchKeySHA256: proposal.MatchKeySHA256,
			SourceRefs:     sortedSourceRefs(proposal.SourceRefs),
		})
	}
	sort.Slice(records, func(i, j int) bool {
		if records[i].Entity != records[j].Entity {
			return records[i].Entity < records[j].Entity
		}
		return records[i].PlatformID < records[j].PlatformID
	})
	reportJSON, err := MarshalReport(report)
	if err != nil {
		return Manifest{}, fmt.Errorf("encode source report: %w", err)
	}
	manifest := Manifest{
		SchemaVersion: SchemaVersion,
		ReportSHA256:  digestBytes(reportJSON),
		Scope:         FixtureOnlyScope,
		Records:       records,
	}
	manifest.ManifestID = manifestIdentity(manifest)
	return manifest, nil
}

// ApproveManifest adds explicit operator authorization. The caller must
// supply the actual approval time and reason; no historical fact is invented.
func ApproveManifest(manifest Manifest, operatorID, reason string, approvedAt time.Time) (Manifest, error) {
	if err := validateManifestIdentity(manifest); err != nil {
		return Manifest{}, err
	}
	if strings.TrimSpace(operatorID) == "" || strings.TrimSpace(reason) == "" || approvedAt.IsZero() {
		return Manifest{}, ErrManifestApprovalRequired
	}
	manifest.Approval = &ManifestApproval{
		OperatorID: strings.TrimSpace(operatorID),
		ApprovedAt: approvedAt.UTC().Format(time.RFC3339Nano),
		Reason:     strings.TrimSpace(reason),
		Scope:      FixtureOnlyScope,
	}
	manifest.ManifestID = manifestIdentity(manifest)
	return manifest, nil
}

// SignManifest signs the complete approved manifest with Ed25519.
func SignManifest(manifest Manifest, privateKey ed25519.PrivateKey) (SignedManifest, error) {
	if len(privateKey) != ed25519.PrivateKeySize {
		return SignedManifest{}, ErrManifestSignature
	}
	if err := validateApprovedManifest(manifest); err != nil {
		return SignedManifest{}, err
	}
	payload, err := canonicalManifest(manifest)
	if err != nil {
		return SignedManifest{}, fmt.Errorf("encode manifest: %w", err)
	}
	signature := ed25519.Sign(privateKey, payload)
	return SignedManifest{
		Manifest:  manifest,
		Algorithm: "Ed25519",
		Signature: base64.RawURLEncoding.EncodeToString(signature),
	}, nil
}

// VerifySignedManifest verifies signature, approval, scope, record ordering
// and manifest identity before any fixture state can be changed.
func VerifySignedManifest(signed SignedManifest, publicKey ed25519.PublicKey) error {
	if len(publicKey) != ed25519.PublicKeySize || signed.Algorithm != "Ed25519" {
		return ErrManifestSignature
	}
	if err := validateApprovedManifest(signed.Manifest); err != nil {
		return err
	}
	signature, err := base64.RawURLEncoding.DecodeString(signed.Signature)
	if err != nil || !ed25519.Verify(publicKey, mustCanonicalManifest(signed.Manifest), signature) {
		return ErrManifestSignature
	}
	return nil
}

type checkpoint struct {
	ManifestID     string `json:"manifest_id"`
	NextIndex      int    `json:"next_index"`
	AppliedCount   int    `json:"applied_count"`
	LastPlatformID string `json:"last_platform_id,omitempty"`
	Status         string `json:"status"`
	Integrity      string `json:"integrity"`
}

// Checkpoint is a public read-only projection of fixture progress. Its
// integrity field is an HMAC and must not be recomputed by callers.
type Checkpoint struct {
	ManifestID     string `json:"manifest_id"`
	NextIndex      int    `json:"next_index"`
	AppliedCount   int    `json:"applied_count"`
	LastPlatformID string `json:"last_platform_id,omitempty"`
	Status         string `json:"status"`
	Integrity      string `json:"integrity"`
}

type appliedRecord struct {
	ManifestID string         `json:"manifest_id"`
	Record     ManifestRecord `json:"record"`
	Order      int            `json:"order"`
}

// AppliedRecord is an immutable fixture-state observation used by tests and
// audit tooling.
type AppliedRecord struct {
	ManifestID string         `json:"manifest_id"`
	Record     ManifestRecord `json:"record"`
	Order      int            `json:"order"`
}

// AuditEntry retains apply/rollback history after fixture records are
// compensated. The caller supplies the actual execution time.
type AuditEntry struct {
	Event      string `json:"event"`
	ManifestID string `json:"manifest_id"`
	PlatformID string `json:"platform_id,omitempty"`
	OccurredAt string `json:"occurred_at"`
}

// ImportResult describes one fixture execution without exposing mutable
// importer internals.
type ImportResult struct {
	Status     string     `json:"status"`
	Applied    int        `json:"applied"`
	Skipped    int        `json:"skipped"`
	Checkpoint Checkpoint `json:"checkpoint"`
}

// FixtureImporter is a disposable, in-memory rehearsal. It deliberately has
// no SQL, file, network or product-repository dependency.
type FixtureImporter struct {
	checkpointKey []byte
	checkpoint    checkpoint
	records       map[string]appliedRecord
	audit         []AuditEntry
}

// NewFixtureImporter creates an empty importer with a private checkpoint MAC
// key. The key is supplied by the fixture harness and never logged.
func NewFixtureImporter(checkpointKey []byte) (*FixtureImporter, error) {
	if len(checkpointKey) < 32 {
		return nil, ErrInvalidCheckpointKey
	}
	importer := &FixtureImporter{
		checkpointKey: append([]byte(nil), checkpointKey...),
		records:       make(map[string]appliedRecord),
	}
	importer.checkpoint = checkpoint{Status: checkpointNew}
	importer.sealCheckpoint()
	return importer, nil
}

// Apply verifies and applies at most limit records. A non-positive limit means
// all remaining records. Every record and checkpoint update is committed in
// memory as one step, so a paused run can be resumed without loss.
func (i *FixtureImporter) Apply(signed SignedManifest, publicKey ed25519.PublicKey, at time.Time, limit int) (ImportResult, error) {
	if err := VerifySignedManifest(signed, publicKey); err != nil {
		return ImportResult{}, err
	}
	if at.IsZero() {
		return ImportResult{}, ErrInvalidExecutionTime
	}
	if err := i.verifyCheckpoint(); err != nil {
		return ImportResult{}, err
	}
	if i.checkpoint.Status == checkpointRolledBack {
		return ImportResult{}, ErrImportAlreadyReversed
	}
	if i.checkpoint.Status != checkpointNew && i.checkpoint.ManifestID != signed.Manifest.ManifestID {
		return ImportResult{}, ErrCheckpointManifest
	}
	if i.checkpoint.Status == checkpointCompleted {
		return ImportResult{Status: ImportStatusIdempotent, Skipped: len(signed.Manifest.Records), Checkpoint: i.publicCheckpoint()}, nil
	}
	if i.checkpoint.Status == checkpointNew {
		i.checkpoint.ManifestID = signed.Manifest.ManifestID
		i.checkpoint.Status = checkpointRunning
	}
	if limit <= 0 {
		limit = len(signed.Manifest.Records) - i.checkpoint.NextIndex
	}
	applied := 0
	for i.checkpoint.NextIndex < len(signed.Manifest.Records) && applied < limit {
		index := i.checkpoint.NextIndex
		record := signed.Manifest.Records[index]
		if _, exists := i.records[record.PlatformID]; exists {
			return ImportResult{}, ErrCheckpointIntegrity
		}
		i.records[record.PlatformID] = appliedRecord{ManifestID: signed.Manifest.ManifestID, Record: cloneManifestRecord(record), Order: index}
		i.audit = append(i.audit, AuditEntry{Event: "fixture_import_applied", ManifestID: signed.Manifest.ManifestID, PlatformID: record.PlatformID, OccurredAt: at.UTC().Format(time.RFC3339Nano)})
		i.checkpoint.NextIndex++
		i.checkpoint.AppliedCount++
		i.checkpoint.LastPlatformID = record.PlatformID
		i.checkpoint.Status = checkpointRunning
		i.sealCheckpoint()
		applied++
	}
	if i.checkpoint.NextIndex == len(signed.Manifest.Records) {
		i.checkpoint.Status = checkpointCompleted
		i.sealCheckpoint()
		return ImportResult{Status: ImportStatusCompleted, Applied: applied, Checkpoint: i.publicCheckpoint()}, nil
	}
	i.checkpoint.Status = checkpointPaused
	i.sealCheckpoint()
	return ImportResult{Status: ImportStatusPaused, Applied: applied, Checkpoint: i.publicCheckpoint()}, nil
}

// Rollback compensates only records belonging to the verified fixture
// manifest. Audit entries and the signed manifest remain available.
func (i *FixtureImporter) Rollback(signed SignedManifest, publicKey ed25519.PublicKey, at time.Time) (ImportResult, error) {
	if err := VerifySignedManifest(signed, publicKey); err != nil {
		return ImportResult{}, err
	}
	if at.IsZero() {
		return ImportResult{}, ErrInvalidExecutionTime
	}
	if err := i.verifyCheckpoint(); err != nil {
		return ImportResult{}, err
	}
	if i.checkpoint.Status == checkpointNew || i.checkpoint.Status == checkpointRolledBack {
		return ImportResult{Status: ImportStatusRolledBack, Checkpoint: i.publicCheckpoint()}, nil
	}
	if i.checkpoint.ManifestID != signed.Manifest.ManifestID {
		return ImportResult{}, ErrCheckpointManifest
	}
	removed := 0
	for platformID, record := range i.records {
		if record.ManifestID != signed.Manifest.ManifestID {
			continue
		}
		delete(i.records, platformID)
		removed++
	}
	i.audit = append(i.audit, AuditEntry{Event: "fixture_import_rolled_back", ManifestID: signed.Manifest.ManifestID, OccurredAt: at.UTC().Format(time.RFC3339Nano)})
	i.checkpoint = checkpoint{ManifestID: signed.Manifest.ManifestID, Status: checkpointRolledBack}
	i.sealCheckpoint()
	return ImportResult{Status: ImportStatusRolledBack, Skipped: removed, Checkpoint: i.publicCheckpoint()}, nil
}

func (i *FixtureImporter) Checkpoint() Checkpoint { return i.publicCheckpoint() }

func (i *FixtureImporter) Snapshot() []AppliedRecord {
	result := make([]AppliedRecord, 0, len(i.records))
	for _, record := range i.records {
		result = append(result, AppliedRecord{ManifestID: record.ManifestID, Record: cloneManifestRecord(record.Record), Order: record.Order})
	}
	sort.Slice(result, func(a, b int) bool { return result[a].Order < result[b].Order })
	return result
}

func (i *FixtureImporter) Audit() []AuditEntry {
	return append([]AuditEntry(nil), i.audit...)
}

func (i *FixtureImporter) verifyCheckpoint() error {
	if i.checkpoint.Integrity == "" || !hmac.Equal([]byte(i.checkpoint.Integrity), []byte(i.checkpointMAC())) {
		return ErrCheckpointIntegrity
	}
	if i.checkpoint.NextIndex < 0 || i.checkpoint.AppliedCount < 0 || i.checkpoint.AppliedCount != i.checkpoint.NextIndex {
		return ErrCheckpointIntegrity
	}
	switch i.checkpoint.Status {
	case checkpointNew:
		if i.checkpoint.ManifestID != "" || i.checkpoint.NextIndex != 0 || i.checkpoint.AppliedCount != 0 {
			return ErrCheckpointIntegrity
		}
	case checkpointRunning, checkpointPaused, checkpointCompleted, checkpointRolledBack:
		if i.checkpoint.ManifestID == "" {
			return ErrCheckpointIntegrity
		}
	default:
		return ErrCheckpointIntegrity
	}
	return nil
}

func (i *FixtureImporter) sealCheckpoint() {
	i.checkpoint.Integrity = i.checkpointMAC()
}

func (i *FixtureImporter) checkpointMAC() string {
	unsigned := i.checkpoint
	unsigned.Integrity = ""
	encoded, _ := json.Marshal(unsigned)
	mac := hmac.New(sha256.New, i.checkpointKey)
	_, _ = mac.Write(encoded)
	return hex.EncodeToString(mac.Sum(nil))
}

func (i *FixtureImporter) publicCheckpoint() Checkpoint {
	return Checkpoint{
		ManifestID:     i.checkpoint.ManifestID,
		NextIndex:      i.checkpoint.NextIndex,
		AppliedCount:   i.checkpoint.AppliedCount,
		LastPlatformID: i.checkpoint.LastPlatformID,
		Status:         i.checkpoint.Status,
		Integrity:      i.checkpoint.Integrity,
	}
}

func validateApprovedManifest(manifest Manifest) error {
	if err := validateManifestIdentity(manifest); err != nil {
		return err
	}
	if manifest.Approval == nil || manifest.Approval.Scope != FixtureOnlyScope || strings.TrimSpace(manifest.Approval.OperatorID) == "" || strings.TrimSpace(manifest.Approval.Reason) == "" {
		return ErrManifestApprovalRequired
	}
	if _, err := time.Parse(time.RFC3339Nano, manifest.Approval.ApprovedAt); err != nil {
		return ErrManifestApprovalRequired
	}
	return nil
}

func validateManifestIdentity(manifest Manifest) error {
	if manifest.SchemaVersion != SchemaVersion || manifest.Scope != FixtureOnlyScope || !isSHA256Hex(manifest.ManifestID) || !isSHA256Hex(manifest.ReportSHA256) || len(manifest.Records) == 0 {
		return ErrManifestIntegrity
	}
	if manifest.ManifestID != manifestIdentity(manifest) {
		return ErrManifestIntegrity
	}
	seenPlatformIDs := make(map[string]struct{}, len(manifest.Records))
	for index, record := range manifest.Records {
		if !validEntity(record.Entity) || record.PlatformID == "" || !isSHA256Hex(record.MatchKeySHA256) || len(record.SourceRefs) == 0 {
			return ErrManifestIntegrity
		}
		if _, exists := seenPlatformIDs[record.PlatformID]; exists {
			return ErrManifestIntegrity
		}
		seenPlatformIDs[record.PlatformID] = struct{}{}
		if index > 0 && manifestRecordLess(record, manifest.Records[index-1]) {
			return ErrManifestIntegrity
		}
		for _, ref := range record.SourceRefs {
			if (ref.Source != SourceCTRL && ref.Source != SourceIMS) || !isSourceSHA(ref.SourceVersion) || strings.TrimSpace(ref.SourceID) == "" {
				return ErrManifestIntegrity
			}
		}
	}
	return nil
}

func manifestIdentity(manifest Manifest) string {
	unsigned := manifest
	unsigned.ManifestID = ""
	encoded, _ := canonicalManifest(unsigned)
	return digestBytes(encoded)
}

func canonicalManifest(manifest Manifest) ([]byte, error) {
	return json.Marshal(manifest)
}

func mustCanonicalManifest(manifest Manifest) []byte {
	encoded, _ := canonicalManifest(manifest)
	return encoded
}

func digestBytes(value []byte) string {
	sum := sha256.Sum256(value)
	return hex.EncodeToString(sum[:])
}

func isSHA256Hex(value string) bool {
	if len(value) != sha256.Size*2 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}

func manifestRecordLess(left, right ManifestRecord) bool {
	if left.Entity != right.Entity {
		return left.Entity < right.Entity
	}
	return left.PlatformID < right.PlatformID
}

func cloneSourceRefs(refs []SourceRef) []SourceRef {
	return append([]SourceRef(nil), refs...)
}

func sortedSourceRefs(refs []SourceRef) []SourceRef {
	result := cloneSourceRefs(refs)
	sort.Slice(result, func(i, j int) bool {
		if result[i].Source != result[j].Source {
			return result[i].Source < result[j].Source
		}
		if result[i].SourceVersion != result[j].SourceVersion {
			return result[i].SourceVersion < result[j].SourceVersion
		}
		return result[i].SourceID < result[j].SourceID
	})
	return result
}

func cloneManifestRecord(record ManifestRecord) ManifestRecord {
	record.SourceRefs = cloneSourceRefs(record.SourceRefs)
	return record
}
